[config]
schemaVersion = "0.0.1"

[package]
namespace = "innominata"
name = "GS2_Cheats"
versionNumber = "1.1.7"
description = "v1.1.7. Update for GS 2.8.2"
websiteUrl = "https://customizing.space"
containsNsfwContent = false

[package.dependencies]
"xiaoye97-BepInEx" = "5.4.17"
"Galactic_Scale-GalacticScale" = "2.8.2"

[build]
icon = "./Package/icon.png"
readme = "./Package/README.md"
outdir = "./"
[[build.copy]]
source = "/obj/Debug/net480/GS2Cheats.dll"
target = "./GS2Cheats.dll"
[publish]
repository = "https://dsp.thunderstore.io"
communities = ["dyson-sphere-program"]
categories = []
